# Generated by Django 5.2.13 on 2026-05-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ім'я")),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("np_warehouse", "Нова Пошта — відділення"),
                            ("np_postamat", "Нова Пошта — поштомат"),
                            ("np_courier", "Нова Пошта — адресна"),
                        ],
                        default="np_warehouse",
                        max_length=20,
                        verbose_name="Спосіб доставки",
                    ),
                ),
                (
                    "np_city_ref",
                    models.CharField(blank=True, max_length=40, verbose_name="Ref міста НП"),
                ),
                (
                    "np_city_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Місто"),
                ),
                (
                    "np_warehouse_ref",
                    models.CharField(blank=True, max_length=40, verbose_name="Ref відділення НП"),
                ),
                (
                    "np_warehouse_address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Відділення / адреса"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн-оплата"),
                            ("cod", "Накладений платіж (передоплата 20%)"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Спосіб оплати",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=30, verbose_name="Статус оплати"),
                ),
                (
                    "payment_ref",
                    models.CharField(blank=True, max_length=100, verbose_name="Реф. оплати"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нове"),
                            ("confirmed", "Підтверджено"),
                            ("paid", "Оплачено"),
                            ("processing", "Комплектується"),
                            ("shipped", "Відправлено"),
                            ("delivered", "Доставлено"),
                            ("cancelled", "Скасовано"),
                            ("returned", "Повернуто"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "np_tracking_number",
                    models.CharField(blank=True, max_length=30, verbose_name="ТТН Нова Пошта"),
                ),
                ("total_uah", models.PositiveIntegerField(default=0, verbose_name="Сума (грн)")),
                ("note", models.TextField(blank=True, verbose_name="Примітка клієнта")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "series_name",
                    models.CharField(max_length=120, verbose_name="Назва серії (знімок)"),
                ),
                ("variant_sku", models.CharField(max_length=64, verbose_name="SKU варіанту")),
                ("color_name", models.CharField(max_length=60, verbose_name="Колір")),
                ("size_display", models.CharField(max_length=30, verbose_name="Розмір")),
                ("quantity", models.PositiveSmallIntegerField(default=1, verbose_name="Кількість")),
                ("price_uah", models.PositiveIntegerField(verbose_name="Ціна за одиницю (грн)")),
                ("is_per_meter", models.BooleanField(default=False, verbose_name="На відріз")),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Довжина (м)",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиція замовлення",
                "verbose_name_plural": "Позиції замовлення",
            },
        ),
    ]
