# Generated by Django 5.2.13 on 2026-05-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("name", models.CharField(max_length=80, verbose_name="Назва")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Рубрика блогу",
                "verbose_name_plural": "Рубрики блогу",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Назва")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Категорія FAQ",
                "verbose_name_plural": "Категорії FAQ",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("delivery", "Доставка та оплата"),
                            ("about", "Про нас"),
                            ("contacts", "Контакти"),
                            ("guarantee", "Гарантії та повернення"),
                            ("how-to-choose", "Як вибрати килим"),
                            ("care", "Догляд за килимом"),
                        ],
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("title_uk", models.CharField(max_length=200, null=True, verbose_name="Заголовок")),
                ("title_en", models.CharField(max_length=200, null=True, verbose_name="Заголовок")),
                ("body", models.TextField(verbose_name="Вміст")),
                ("body_uk", models.TextField(null=True, verbose_name="Вміст")),
                ("body_en", models.TextField(null=True, verbose_name="Вміст")),
                (
                    "seo_title",
                    models.CharField(blank=True, max_length=180, verbose_name="SEO Title"),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=300, verbose_name="SEO Description"),
                ),
                (
                    "seo_description_uk",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_description_en",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Статична сторінка",
                "verbose_name_plural": "Статичні сторінки",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("title_uk", models.CharField(max_length=200, null=True, verbose_name="Заголовок")),
                ("title_en", models.CharField(max_length=200, null=True, verbose_name="Заголовок")),
                (
                    "cover",
                    models.ImageField(blank=True, upload_to="articles/", verbose_name="Обкладинка"),
                ),
                (
                    "excerpt",
                    models.CharField(blank=True, max_length=300, verbose_name="Короткий опис"),
                ),
                (
                    "excerpt_uk",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Короткий опис"
                    ),
                ),
                (
                    "excerpt_en",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Короткий опис"
                    ),
                ),
                ("body", models.TextField(verbose_name="Текст статті")),
                ("body_uk", models.TextField(null=True, verbose_name="Текст статті")),
                ("body_en", models.TextField(null=True, verbose_name="Текст статті")),
                (
                    "seo_title",
                    models.CharField(blank=True, max_length=180, verbose_name="SEO Title"),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=300, verbose_name="SEO Description"),
                ),
                (
                    "seo_description_uk",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_description_en",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(db_index=True, default=False, verbose_name="Опубліковано"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата публікації"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_facets",
                    models.ManyToManyField(
                        blank=True, to="catalog.facet", verbose_name="Пов'язані фасети"
                    ),
                ),
                (
                    "related_series",
                    models.ManyToManyField(
                        blank=True, to="catalog.productseries", verbose_name="Пов'язані товари"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="content.articlecategory",
                        verbose_name="Рубрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стаття",
                "verbose_name_plural": "Статті",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Питання")),
                (
                    "question_uk",
                    models.CharField(max_length=300, null=True, verbose_name="Питання"),
                ),
                (
                    "question_en",
                    models.CharField(max_length=300, null=True, verbose_name="Питання"),
                ),
                ("answer", models.TextField(verbose_name="Відповідь")),
                ("answer_uk", models.TextField(null=True, verbose_name="Відповідь")),
                ("answer_en", models.TextField(null=True, verbose_name="Відповідь")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активний")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="content.faqcategory",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ питання",
                "verbose_name_plural": "FAQ питання",
                "ordering": ["category__sort_order", "sort_order"],
            },
        ),
    ]
