# Generated by Django 5.2.13 on 2026-05-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+380XXXXXXXXX", max_length=32, verbose_name="Телефон"
                    ),
                ),
                (
                    "phone_display",
                    models.CharField(
                        default="+380 (XX) XXX-XX-XX",
                        max_length=40,
                        verbose_name="Телефон для відображення",
                    ),
                ),
                (
                    "work_hours",
                    models.CharField(
                        default="Пн–Пт 9:00–19:00, Сб 10:00–18:00",
                        max_length=120,
                        verbose_name="Графік роботи",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@kylymy.ua", max_length=254, verbose_name="Email"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, verbose_name="Адреса")),
                ("instagram_url", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                ("tiktok_url", models.URLField(blank=True, verbose_name="TikTok")),
                (
                    "gtm_id",
                    models.CharField(
                        blank=True, help_text="GTM-XXXXXXX", max_length=20, verbose_name="GTM ID"
                    ),
                ),
                (
                    "meta_pixel_id",
                    models.CharField(blank=True, max_length=20, verbose_name="Meta Pixel ID"),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Юр. назва"),
                ),
                ("company_iban", models.CharField(blank=True, max_length=40, verbose_name="IBAN")),
                (
                    "company_edrpou",
                    models.CharField(blank=True, max_length=20, verbose_name="ЄДРПОУ"),
                ),
                (
                    "free_delivery_threshold",
                    models.PositiveIntegerField(
                        default=1500, verbose_name="Безкоштовна доставка від (грн)"
                    ),
                ),
                (
                    "delivery_price",
                    models.PositiveIntegerField(default=70, verbose_name="Ціна доставки (грн)"),
                ),
                (
                    "return_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Повернення протягом (днів)"
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="Kupyty kylym v Ukraini — Kylymy",
                        max_length=180,
                        verbose_name="Title сайту",
                    ),
                ),
                (
                    "site_description",
                    models.CharField(blank=True, max_length=300, verbose_name="Description сайту"),
                ),
            ],
            options={
                "verbose_name": "Налаштування сайту",
                "verbose_name_plural": "Налаштування сайту",
            },
        ),
    ]
