# Generated by Django 5.2.13 on 2026-05-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Ім'я")),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                ("page_url", models.URLField(blank=True, verbose_name="URL сторінки")),
                ("note", models.TextField(blank=True, verbose_name="Примітка")),
                (
                    "is_processed",
                    models.BooleanField(db_index=True, default=False, verbose_name="Оброблено"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.productseries",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запит на дзвінок",
                "verbose_name_plural": "Запити на дзвінок",
                "ordering": ["-created_at"],
            },
        ),
    ]
