# Generated by Django 5.2.13 on 2026-05-04 13:05

import apps.catalog.models.media
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True, verbose_name="URL (slug)")),
                ("name", models.CharField(max_length=80, verbose_name="Назва")),
                ("name_uk", models.CharField(max_length=80, null=True, verbose_name="Назва")),
                ("name_en", models.CharField(max_length=80, null=True, verbose_name="Назва")),
                (
                    "name_genitive",
                    models.CharField(
                        blank=True,
                        help_text="Для шаблонів: 'купити {kilymiv}'",
                        max_length=80,
                        verbose_name="Назва у родовому відмінку",
                    ),
                ),
                (
                    "name_genitive_uk",
                    models.CharField(
                        blank=True,
                        help_text="Для шаблонів: 'купити {kilymiv}'",
                        max_length=80,
                        null=True,
                        verbose_name="Назва у родовому відмінку",
                    ),
                ),
                (
                    "name_genitive_en",
                    models.CharField(
                        blank=True,
                        help_text="Для шаблонів: 'купити {kilymiv}'",
                        max_length=80,
                        null=True,
                        verbose_name="Назва у родовому відмінку",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Іконка (Material Symbols)"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(blank=True, max_length=180, verbose_name="SEO Title"),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=300, verbose_name="SEO Description"),
                ),
                (
                    "seo_description_uk",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_description_en",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_text",
                    models.TextField(blank=True, verbose_name="SEO-текст (внизу каталогу)"),
                ),
                (
                    "seo_text_uk",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO-текст (внизу каталогу)"
                    ),
                ),
                (
                    "seo_text_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO-текст (внизу каталогу)"
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активний")),
            ],
            options={
                "verbose_name": "Розділ",
                "verbose_name_plural": "Розділи",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Facet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("category", "Тип / матеріал"),
                            ("purpose", "Призначення"),
                            ("style", "Стиль"),
                            ("form", "Форма"),
                            ("size", "Розмір"),
                            ("color", "Колір"),
                            ("manufacturer", "Виробник"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Тип фасету",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="URL (slug)")),
                ("name", models.CharField(max_length=100, verbose_name="Назва")),
                ("name_uk", models.CharField(max_length=100, null=True, verbose_name="Назва")),
                ("name_en", models.CharField(max_length=100, null=True, verbose_name="Назва")),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text="#RRGGBB, тільки для type=color",
                        max_length=7,
                        verbose_name="HEX-колір (для swатчу)",
                    ),
                ),
                (
                    "is_indexable",
                    models.BooleanField(
                        default=True, verbose_name="Індексувати як окрему SEO-сторінку"
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "seo_title",
                    models.CharField(blank=True, max_length=180, verbose_name="SEO Title"),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=300, verbose_name="SEO Description"),
                ),
                (
                    "seo_description_uk",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_description_en",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_text",
                    models.TextField(blank=True, verbose_name="SEO-текст (внизу каталогу)"),
                ),
                (
                    "seo_text_uk",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO-текст (внизу каталогу)"
                    ),
                ),
                (
                    "seo_text_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO-текст (внизу каталогу)"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.facet",
                        verbose_name="Батьківський фасет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фасет",
                "verbose_name_plural": "Фасети",
                "ordering": ["type", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=120, verbose_name="URL (slug)")),
                ("name", models.CharField(max_length=120, verbose_name="Назва серії")),
                (
                    "name_uk",
                    models.CharField(max_length=120, null=True, verbose_name="Назва серії"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=120, null=True, verbose_name="Назва серії"),
                ),
                ("short_descr", models.TextField(blank=True, verbose_name="Короткий опис")),
                (
                    "short_descr_uk",
                    models.TextField(blank=True, null=True, verbose_name="Короткий опис"),
                ),
                (
                    "short_descr_en",
                    models.TextField(blank=True, null=True, verbose_name="Короткий опис"),
                ),
                ("full_descr", models.TextField(blank=True, verbose_name="Повний опис")),
                (
                    "full_descr_uk",
                    models.TextField(blank=True, null=True, verbose_name="Повний опис"),
                ),
                (
                    "full_descr_en",
                    models.TextField(blank=True, null=True, verbose_name="Повний опис"),
                ),
                (
                    "care_instructions",
                    models.TextField(blank=True, verbose_name="Догляд та чищення"),
                ),
                (
                    "care_instructions_uk",
                    models.TextField(blank=True, null=True, verbose_name="Догляд та чищення"),
                ),
                (
                    "care_instructions_en",
                    models.TextField(blank=True, null=True, verbose_name="Догляд та чищення"),
                ),
                (
                    "pile_height_mm",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Висота ворсу (мм)"
                    ),
                ),
                (
                    "pile_type",
                    models.CharField(blank=True, max_length=80, verbose_name="Тип ворсу"),
                ),
                (
                    "base_material",
                    models.CharField(blank=True, max_length=80, verbose_name="Матеріал основи"),
                ),
                ("composition", models.CharField(blank=True, max_length=120, verbose_name="Склад")),
                (
                    "country",
                    models.CharField(blank=True, max_length=40, verbose_name="Країна-виробник"),
                ),
                (
                    "manufacturer_brand",
                    models.CharField(blank=True, max_length=80, verbose_name="Бренд виробника"),
                ),
                (
                    "weight_per_m2",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Вага (г/м²)"),
                ),
                (
                    "density",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Щільність (точок/м²)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Активний"),
                ),
                ("is_top", models.BooleanField(default=False, verbose_name="Топ")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Знижка %"),
                ),
                (
                    "seo_title",
                    models.CharField(blank=True, max_length=180, verbose_name="SEO Title"),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=300, verbose_name="SEO Description"),
                ),
                (
                    "seo_description_uk",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_description_en",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Переглядів"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="series",
                        to="catalog.facet",
                        verbose_name="Фасети (тип/стиль/призначення/форма/виробник)",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="catalog.section",
                        verbose_name="Розділ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Серія товарів",
                "verbose_name_plural": "Серії товарів",
                "ordering": ["-is_top", "-is_new", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(max_length=64, unique=True, verbose_name="Артикул (SKU)")),
                ("width_cm", models.PositiveSmallIntegerField(verbose_name="Ширина (см)")),
                (
                    "length_cm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Залишити порожнім для продажу на відріз (пог.м)",
                        null=True,
                        verbose_name="Довжина (см)",
                    ),
                ),
                (
                    "is_per_meter",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Продається на відріз (пог.м)"
                    ),
                ),
                ("price_uah", models.PositiveIntegerField(verbose_name="Ціна (грн)")),
                (
                    "old_price_uah",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Стара ціна (грн)"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Залишок")),
                (
                    "in_stock",
                    models.BooleanField(db_index=True, default=True, verbose_name="В наявності"),
                ),
                (
                    "ready_to_ship",
                    models.BooleanField(default=True, verbose_name="Готово до відправки"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        limit_choices_to={"type": "color"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variant_colors",
                        to="catalog.facet",
                        verbose_name="Колір",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.productseries",
                        verbose_name="Серія",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "size"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variant_sizes",
                        to="catalog.facet",
                        verbose_name="Розмір",
                    ),
                ),
            ],
            options={
                "verbose_name": "Варіант товару",
                "verbose_name_plural": "Варіанти товарів",
                "ordering": ["sort_order", "width_cm", "length_cm"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.catalog.models.media.series_image_path, verbose_name="Фото"
                    ),
                ),
                (
                    "image_webp",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        upload_to="products/webp/",
                        verbose_name="WebP версія",
                    ),
                ),
                (
                    "image_thumb",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        upload_to="products/thumb/",
                        verbose_name="Мініатюра",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="Залишити порожнім для автогенерації з назви серії",
                        max_length=160,
                        verbose_name="Alt-текст",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="Головне фото")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.productseries",
                        verbose_name="Серія",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.productvariant",
                        verbose_name="Варіант (опційно)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото товару",
                "verbose_name_plural": "Фото товарів",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="facet",
            index=models.Index(fields=["type", "is_indexable"], name="catalog_fac_type_aaf8a9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="facet",
            unique_together={("type", "slug")},
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["series", "in_stock"], name="catalog_pro_series__0ac52a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productseries",
            index=models.Index(
                fields=["section", "is_active"], name="catalog_pro_section_3ac26e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productseries",
            index=models.Index(fields=["is_top", "is_new"], name="catalog_pro_is_top_104503_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productseries",
            unique_together={("section", "slug")},
        ),
    ]
