# Generated by Django 5.2.13 on 2026-05-04 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("author_name", models.CharField(max_length=80, verbose_name="Ім'я")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оцінка (1-5)",
                    ),
                ),
                ("body", models.TextField(verbose_name="Текст відгуку")),
                ("photo", models.ImageField(blank=True, upload_to="reviews/", verbose_name="Фото")),
                (
                    "is_approved",
                    models.BooleanField(db_index=True, default=False, verbose_name="Схвалено"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.productseries",
                        verbose_name="Серія товарів",
                    ),
                ),
            ],
            options={
                "verbose_name": "Відгук",
                "verbose_name_plural": "Відгуки",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["series", "is_approved"], name="reviews_rev_series__a62236_idx"
                    )
                ],
            },
        ),
    ]
